blog/urls.py
from django.conf.urls import url
from blog import views
from django.contrib.auth import views as auth_view

urlpatterns = [
    url(r'^$', views.PostListView.as_view(), name='post_list'),
    url(r'^post/(?P<pk>\d+)$', views.PostDetailView.as_view(), name='post_detail'),
    url(r'^post/new/$', views.CreatePostView.as_view(), name='post_new'),
    url(r'^post/(?P<pk>\d+)/edit/$', views.PostUpdateView.as_view(), name='post_edit'),
    url(r'^post/(?P<pk>\d+)/remove/$', views.PostDeleteView.as_view(), name='post_remove'),
    url(r'^post/(?P<pk>\d+)/comment/$', views.add_comment_to_post, name='add_comment_to_post'),
    url(r'^post/(?P<pk>\d+)/publish/$', views.post_publish, name='post_publish'),
    url(r'^post/(?P<pk>\d+)/un_publish/$', views.un_publish, name='post_unpublish'),
    url(r'^comment/(?P<pk>\d+)/approve', views.comment_approve, name='comment_approve'),
    url(r'^comment/(?P<pk>\d+)/remove', views.comment_remove, name='comment_remove'),
    url(r'^drafts/$', views.DraftListView.as_view(), name='post_draft_list'),

    url(r'^accounts/login/$', auth_view.LoginView.as_view(template_name='login.html'), name='login'),
    url(r'^accounts/logout/$', auth_view.LogoutView.as_view(), name='logout', kwargs={'next_page': '/'})
]

django_site/urls.py
from django.contrib import admin
from django.urls import path
from django.conf.urls import include, url
from base_app import views as base_views


urlpatterns = [
    url(r'^admin/', admin.site.urls),
    url(r'^$', base_views.index, name='index'),
    url(r'^about/$', base_views.about, name='about'),
    url(r'^my_blog/', include('blog.urls')),
    url(r'^social_mdeia/', include('simple_social.urls')),
]

simple_social/urls.py
from django.conf.urls import url, include
from simple_social import views

urlpatterns = [
    url(r'^$', views.HomePage.as_view(), name='social_home'),
    url(r'accounts/', include('social_account.urls', namespace='accounts')),
    url(r'accounts/', include('django.contrib.auth.urls')),
    url(r'test/$', views.TestPage.as_view(), name='test'),
    url(r'thanks/$', views.ThanksPage.as_view(), name='thanks'),
    url(r"^posts/", include("social_posts.urls", namespace="posts")),
    url(r"^groups/", include("social_groups.urls", namespace="groups")),
]

social_groups/urls.py
from django.conf.urls import url
from . import views

app_name = 'groups'

urlpatterns = [
    url(r"^$", views.ListGroups.as_view(), name="all"),
    url(r"^new/$", views.CreateGroup.as_view(), name="create"),
    url(r"^posts/in/(?P<slug>[-\w]+)/$", views.SingleGroup.as_view(), name="single"),
    url(r"join/(?P<slug>[-\w]+)/$", views.JoinGroup.as_view(), name="join"),
    url(r"leave/(?P<slug>[-\w]+)/$", views.LeaveGroup.as_view(), name="leave"),
]

social_posts/urls.py
from django.conf.urls import url

from . import views

app_name = 'posts'

urlpatterns = [
    url(r"^$", views.PostList.as_view(), name="all"),
    url(r"new/$", views.CreatePost.as_view(), name="create"),
    url(r"by/(?P<username>[-\w]+)/$", views.UserPosts.as_view(), name="for_user"),
    url(r"by/(?P<username>[-\w]+)/(?P<pk>\d+)/$", views.PostDetail.as_view(), name="single"),
    url(r"delete/(?P<pk>\d+)/$", views.DeletePost.as_view(), name="delete"),
]

simple_social/views.py
from django.shortcuts import render
from django.views.generic import TemplateView

# Create your views here.

class TestPage(TemplateView):
    template_name = 'simple_social/login_test.html'

class ThanksPage(TemplateView):
    template_name = 'simple_social/thanks.html'

class HomePage(TemplateView):
    template_name = 'simple_social/index.html'

templates/simple_social/groups/group_base.html
{% extends 'simple_social/base.html' %}

{% block content %}

    <div class="container">
        <div class="row">
            {% block pregroup %}{% endblock %}
            {% block group_content %}{% endblock %}
            {% block postgroup %}{% endblock %}
        </div>
    </div>

{% endblock %}

templates/simple_social/groups/group_detail.html
{% extends 'simple_social/groups/group_base.html' %}

{% block pregroup %}
    <h1>{{ group.name }}</h1>
    <h2>Member Count: {{ group.members.count }}</h2>

    <div class="content">
        {% if user in group.members.all %}
            <a href="{% url 'groups:leave' slug=group.slug %}"
               class="btn btn-lg btn-fill btn-warning">
            <span class="glyphicon glyphicon-remove-circle">Leave</span>
            </a>
        {% else %}
            <a href="{% url 'groups:join' slug=group.slug %}"
               class="btn btn-lg btn-fill btn-warning">
            <span class="glyphicon glyphicon-ok-circle">Join</span>
            </a>
        {% endif %}
    </div>

{% endblock %}

{% block group_content %}
    {% if group.posts.count == 0 %}
        <div class="col-md-8">
        <h2>No posts in this group yet!</h2>
        </div>
    {% else %}
        {% for post in group.posts.all %}
            {% include "simple_social/posts/_post.html" %}
        {% endfor %}
    {% endif %}
{% endblock %}

templates/simple_social/groups/group_form.html
{% extends 'simple_social/groups/group_base.html' %}
{% load bootstrap3 %}
{% block pregroup %}
    <h4>Create a new group!</h4>
    <form method="POST" action="{% url 'groups:create' %}" id="groupForm">
        {% csrf_token %}
        {% bootstrap_form form %}
        <input type="submit" value="Create" class="btn btn-primary btn-large">
    </form>
{% endblock %}

templates/simple_social/groups/group_list.html
{% extends 'simple_social/groups/group_base.html' %}

{% block pregroup %}
    <div class="col-md-4">
        <div class="content">
            {% if user.is_authenticated %}
                <h2> Welcome Back!
                    <a href="{% url 'posts:for_user' username=user.username %}">@{{ user.username }}</a>
                </h2>
            {% endif %}
            <h2>Groups</h2>
            <p>Welcome to the groups page!</p>
        </div>

        {% if user.is_authenticated %}
            <a href="{% url 'groups:create' %}" class="btn btn-md btn-fill btn-warning">
                <span class="glyphicon glyphicon-plus-sign">Create!</span>
            </a>
        {% endif %}

    </div>
{% endblock %}

{% block group_content %}
    <div class="col-md-8">
        <div class="list-group">
            {% for group in object_list %}
                <a class="list-group-item" href="{% url 'groups:single' slug=group.slug %}">
                    <h3 class="title list-group-item-heading">{{ group.name }}</h3>
                    <div class="list-group-item-text container-fluid">
                        {{ group.description_html|safe }}
                        <div class="row">
                            <div class="col-md-4">
                                <span class="badge">{{ group.members.count }}</span>
                                member{{ group.members.count|pluralize }}
                            </div>
                            <div class="col-md-4">
                                <span class="badge">{{ group.posts.count }}</span>
                                post{{ group.posts.count|pluralize }}
                            </div>
                        </div>
                    </div>
                </a>
            {% endfor %}
        </div>
    </div>
{% endblock %}